/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class Collection : BaseComponent, System.Collections.IList {
  internal new static Collection CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new Collection(cPtr, cMemoryOwn);
  }

  internal Collection(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(Collection obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public object this[int index] {
    get {
      if (index >= Count) {
        throw new ArgumentOutOfRangeException("index");
      }
      return Get(index);
    }
    set {
      if (index >= Count) {
        throw new ArgumentOutOfRangeException("index");
      }
      Set(index, value);
    }
  }
  
  object System.Collections.IList.this[int index] {
    get { return this[index]; }
    set { this[index] = value; }
  }

  int System.Collections.IList.Add(object value) {
    return Add(value);
  }

  bool System.Collections.IList.Contains(object value) {
    return Contains(value);
  }

  void System.Collections.IList.Clear() {
    Clear();
  }

  bool System.Collections.IList.IsReadOnly {
    get { return false; }
  }

  bool System.Collections.IList.IsFixedSize {
    get { return false; }
  }

  int System.Collections.IList.IndexOf(object value) {
    return IndexOf(value);
  }

  void System.Collections.IList.Insert(int index, object value) {
    Insert(index, value);
  }

  void System.Collections.IList.Remove(object value) {
    Remove(value);
  }

  void System.Collections.IList.RemoveAt(int index) {
    RemoveAt(index);
  }

  bool System.Collections.ICollection.IsSynchronized {
    get { return false; }
  }

  object System.Collections.ICollection.SyncRoot {
    get { return null; }
  }

  void System.Collections.ICollection.CopyTo(Array array, int arrayIndex) {
    if (array == null) {
      throw new ArgumentNullException("array");
    }
    if (arrayIndex < 0) {
      throw new ArgumentOutOfRangeException("arrayIndex is less than 0.");
    }
    if ((array != null) && (array.Rank != 1)) {
      throw new ArgumentException("array is multidimensional.");
    }
    if (array.Length + arrayIndex > Count) { 
      throw new ArgumentException("There is no available space in array to copy all elements in the ICollection.");
    }
    int numElements = Count;
    for (int i = 0; i < numElements; ++i) {
      array.SetValue(this[i], arrayIndex + i);
    }
  }

  public System.Collections.IEnumerator GetEnumerator() {
    return new CollectionEnumerator(this);
  }

  private struct CollectionEnumerator : System.Collections.IEnumerator {
    object System.Collections.IEnumerator.Current {
      get { return Current; }
    }
    public object Current {
      get { return this._collection[this._index]; }
    }
    public bool MoveNext() {
      if (++this._index >= this._collection.Count) {
        return false;
      }
      return true;
    }
    public void Reset() {
      this._index = -1;
    }
    public CollectionEnumerator(Collection c) {
      this._collection = c;
      this._index = -1;
    }
    private Collection _collection;
    private int _index;
  }

  public Collection() {
  }

  protected override System.IntPtr CreateCPtr(System.Type type, out bool registerExtend) {
    registerExtend = false;
    return NoesisGUI_PINVOKE.new_Collection__SWIG_0();
  }

  private object Get(int index) {
    IntPtr cPtr = NoesisGUI_PINVOKE.Collection_Get(swigCPtr, index);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return Noesis.Extend.GetProxy(cPtr, false);
  }

  private void Set(int index, object item) {
    NoesisGUI_PINVOKE.Collection_Set(swigCPtr, index, Noesis.Extend.GetInstanceHandle(item));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public int Add(object item) {
    int ret = NoesisGUI_PINVOKE.Collection_Add(swigCPtr, Noesis.Extend.GetInstanceHandle(item));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public void Clear() {
    NoesisGUI_PINVOKE.Collection_Clear(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public bool Contains(object item) {
    bool ret = NoesisGUI_PINVOKE.Collection_Contains(swigCPtr, Noesis.Extend.GetInstanceHandle(item));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public int IndexOf(object item) {
    int ret = NoesisGUI_PINVOKE.Collection_IndexOf(swigCPtr, Noesis.Extend.GetInstanceHandle(item));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public void Insert(int index, object item) {
    NoesisGUI_PINVOKE.Collection_Insert(swigCPtr, index, Noesis.Extend.GetInstanceHandle(item));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public void Remove(object item) {
    NoesisGUI_PINVOKE.Collection_Remove(swigCPtr, Noesis.Extend.GetInstanceHandle(item));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public void RemoveAt(int index) {
    NoesisGUI_PINVOKE.Collection_RemoveAt(swigCPtr, index);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public int Count {
    get {
      int ret = NoesisGUI_PINVOKE.Collection_Count_get(swigCPtr);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
      return ret;
    }
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Collection_GetStaticType();
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

}

}

