/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


namespace Noesis
{

public enum DragDropEffectFlags {
  None = 0x00,
  Copy = 0x01,
  Move = 0x02,
  Link = 0x03,
  Scroll = 0x04,
  All = 0xFF
}

}

