/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


namespace Noesis
{

public enum DragDropKeyStateFlags {
  None = 0x00,
  LeftMouseButton = 0x01,
  RightMouseButton = 0x02,
  ShiftKey = 0x03,
  ControlKey = 0x04,
  MiddleMouseButton = 0x05,
  AltKey = 0x06
}

}

