/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class TraversalRequest : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TraversalRequest(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TraversalRequest obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TraversalRequest() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          if (Noesis.Extend.Initialized) { NoesisGUI_PINVOKE.delete_TraversalRequest(swigCPtr);}
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public FocusNavigationDirection FocusNavigationDirection {
    get {
      return GetFocusNavigationDirectionHelper();
    }
  }

  public bool Wrapped {
    get {
      return GetWrappedHelper();
    }
    set {
      SetWrappedHelper(value);
    }
  }

  private FocusNavigationDirection GetFocusNavigationDirectionHelper() {
    FocusNavigationDirection ret = (FocusNavigationDirection)NoesisGUI_PINVOKE.TraversalRequest_GetFocusNavigationDirectionHelper(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  private bool GetWrappedHelper() {
    bool ret = NoesisGUI_PINVOKE.TraversalRequest_GetWrappedHelper(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  private void SetWrappedHelper(bool w) {
    NoesisGUI_PINVOKE.TraversalRequest_SetWrappedHelper(swigCPtr, w);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public TraversalRequest() : this(NoesisGUI_PINVOKE.new_TraversalRequest(), true) {
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

}

}

